# Cosmological parameters
# Fiducial taken from T. Eifler et al. MNRAS 507, 1746–1761 (2021)
Omega_m : 0.3156
Omega_v : 0.6352 # = 1 - omm - omb
sigma_8 : 0.831
n_spec : 0.9645
w0 : -1.0
wa : 0.0
omb : 0.0492
h0 : 0.6727

# Survey and galaxy parameters

# area in degrees
# n_gal,lens_n_gal in gals/arcmin^2
area : 2413.0 # SAME AS DC1 PAPER
sourcephotoz : multihisto
lensphotoz : multihisto
source_tomobins : 4
lens_tomobins : 4
sigma_e : 0.368 # sqrt{2} * 0.26 ~ 0.36769552621700474
shear_REDSHIFT_FILE : ../../OPTIMAL_TOMO_BINS/nzs/tomobinning_project/true_nz/equipopulated/true_nz_equipopulated_4_bins.nz  
clustering_REDSHIFT_FILE : ../../OPTIMAL_TOMO_BINS/nzs/tomobinning_project/true_nz/equipopulated/true_nz_equipopulated_4_bins.nz  
source_n_gal : 10.33,10.33,10.33,10.33 # 41.3 / 4
lens_n_gal : 10.33,10.33,10.33,10.33 # 41.3 / 4
lens_tomogbias : 1.4,1.5,1.6,1.7 # SAME AS DC1 PAPER b^i_g = 1.4+i*0.1 
lens_tomo_bmag : 0.0,0.0,0.0,0.0 #,0.0,0.0,0.0 ,0.0

# IA parameters: See Eq. 26 of 2004.04702 
IA : 1        # (0 KL)
A_ia : 0.6061   # SAME AS DC1 PAPER
eta_ia : -1.515   # SAME AS DC1 PAPER 
oneplusz0_ia : 1.30     # See page 10 of 2004.04702

# Covariance paramters
# tmin, tmax in arcminutes, and ntheta SAME AS DC1 PAPER
tmin : 2.5
tmax : 250.0
ntheta : 15

ng : 0
cng : 0

outdir : ../../OPTIMAL_TOMO_BINS/covs/tomobinning_project/true_nz/equipopulated/ng0/4_bins/
filename : true_nz_equipopulated_ng0_4_bins
ss : true
ls : true
ll : true
